apiVersion: v1
data:
  add_tag_to_record.lua: |-
    function add_tag_to_record(tag, timestamp, record)
      record["tag"] = tag
      return 1, timestamp, record
    end
  filter-kubernetes.conf: |-
    [FILTER]
        Name                lua
        Match               kubernetes.*
        script              add_tag_to_record.lua
        call                add_tag_to_record

    # Scripts
    [FILTER]
        Name                lua
        Match               kubernetes.*
        script              modify_severity.lua
        call                cb_modify

  fluent-bit.conf: |-
    # Service section

    [SERVICE]
        Flush           30
        Daemon          Off
        Log_Level       info
        Parsers_File    parsers.conf
        HTTP_Server     On
        HTTP_Listen     0.0.0.0
        HTTP_PORT       2020


    @INCLUDE input.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output.conf
  input.conf: |-
    # Input section

    [INPUT]
        Name              tail
        Tag               kubernetes.*
        Path              /var/log/containers/*tf-destroy*.log
        Exclude_Path      *_garden_fluent-bit-*.log,*_garden_loki-*.log
        Parser            docker
        DB                /var/log/flb_kube-test.db
        DB.sync           full
        read_from_head    true
        Skip_Long_Lines   On
        Mem_Buf_Limit     30MB
        Refresh_Interval  10
        Ignore_Older      1800s


  kubernetes_label_map.json: |-
    {
      "kubernetes": {"container_name":"container_name","docker_id":"docker_id","namespace_name":"namespace_name","pod_name":"pod_name"} ,
      "severity": "severity"
    }
  modify_severity.lua: |-
    function cb_modify(tag, timestamp, record)
      local unified_severity = cb_modify_unify_severity(record)

      if not unified_severity then
        return 0, 0, 0
      end

      return 1, timestamp, record
    end

    function cb_modify_unify_severity(record)
      local modified = false
      local severity = record["severity"]
      if severity == nil or severity == "" then
        return modified
      end

      severity = trim(severity):upper()

      if severity == "I" or severity == "INF" or severity == "INFO" then
        record["severity"] = "INFO"
        modified = true
      elseif severity == "W" or severity == "WRN" or severity == "WARN" or severity == "WARNING" then
        record["severity"] = "WARN"
        modified = true
      elseif severity == "E" or severity == "ERR" or severity == "ERROR" or severity == "EROR" then
        record["severity"] = "ERR"
        modified = true
      elseif severity == "D" or severity == "DBG" or severity == "DEBUG" then
        record["severity"] = "DBG"
        modified = true
      elseif severity == "N" or severity == "NOTICE" then
        record["severity"] = "NOTICE"
        modified = true
      elseif severity == "F" or severity == "FATAL" then
        record["severity"] = "FATAL"
        modified = true
      end

      return modified
    end

    function trim(s)
      return (s:gsub("^%s*(.-)%s*$", "%1"))
    end
  output.conf: |-
    # Output section

    [Output]
        Name gardenerloki
        Match kubernetes.*
        Url http://loki.garden.svc:3100/loki/api/v1/push
        LogLevel info
        BatchWait 60
        BatchSize 30720
        Labels {test="fluent-bit-go"}
        LineFormat json
        SortByTimestamp true
        DropSingleKey false
        RemoveKeys kubernetes,stream,type,time,tag
        LabelMapPath /fluent-bit/etc/kubernetes_label_map.json
        MaxRetries 3
        Timeout 10
        MinBackoff 30
        Buffer true
        BufferType dque
        QueueDir  /fluent-bit/buffers
        QueueSegmentSize 300
        QueueSync normal
        QueueName gardener-test
        NumberOfBatchIDs 5
        FallbackToTagWhenMetadataIsMissing true

  parsers.conf: |-
    # Custom parsers
    [PARSER]
        Name        docker
        Format      json
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z
        Time_Keep   On
        # Command      |  Decoder | Field | Optional Action
        # =============|==================|=================
        Decode_Field_As   escaped    log

  plugin.conf: |-
    [PLUGINS]
        Path /fluent-bit/plugins/out_loki.so
kind: ConfigMap
metadata:
  labels:
    app: fluent-bit-test
    role: logging-test
  name: fluent-bit-config-test
  namespace: garden
